### ISSUE TITLE
Uncaught Error: ENAMETOOLONG: name too long, open 'file:///Users/adamprocter/Dropbox/Acting%20Pro...

### ISSUE THREAD

**Issue by adamprocter** [FoldingText/foldingtext-for-atom#57] opened 2015-06-24 14:12 UTC
[Enter steps to reproduce below:]
1. Paste in some text from another source (will paste as linked text (all underlined ?)
2. Pick up and move text

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [foldingtext-for-atom](https://github.com/FoldingText/foldingtext-for-atom) package, v0.6.2
### Stack Trace

Uncaught Error: ENAMETOOLONG: name too long, open 'file:///Users/adamprocter/Dropbox/Acting%20Programme%20Leader%20for%20Games%20Design%20

**Comment by adamprocter** [comment] 2015-06-24 14:17
everything I paste in seems to think it is a link and I have to keep clearing formating

**Comment by jessegrosjean** [comment] 2015-06-25 12:29
Duplicate of #55

**Closed as completed by jessegrosjean** 2015-06-25 12:29 UTC
Labels: bug
